# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-06 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[(b'draft', b'DRAFT'), (b'validate', b'VALIDATE'), (b'done', b'DOne')], default=b'draft', max_length=10)),
            ],
        ),
    ]
